language: go
go:
  - 1.x
sudo: required
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GOOS=linux
    - CGO_ENABLED=0

install: true
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
